from __future__ import annotations

from fastmcp import FastMCP


def register(mcp: FastMCP) -> None:
    @mcp.tool
    async def photo_of_physical_items_like_kitchen_stuff(request: str | None = None) -> dict:
        """Stub tool generated by scripts/agent.py (interactive)."""
        return {
            "summary": "Stub tool created. Implementation pending.",
            "result": {"request": request},
            "next_actions": [
                "Implement tool logic in vm_server/tools/photo_of_physical_items_like_kitchen_stuff.py"
            ],
            "errors": [],
        }
