#!/usr/bin/env bash
# DEPRECATED: moved to legacy/vm during cleanup. Use canonical vm/ scripts instead.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config.sh"

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "Missing vm/config.sh. Copy vm/config.example.sh first." >&2
  exit 1
fi

# shellcheck source=/dev/null
source "$CONFIG_FILE"

if [[ -z "${VM_HOST:-}" || -z "${VM_USER:-}" || -z "${VM_SSH_KEY:-}" ]]; then
  echo "Missing VM_HOST, VM_USER, or VM_SSH_KEY in vm/config.sh." >&2
  exit 1
fi

AREA="${1:-}"
NAME="${2:-}"
DESC="${3:-}"
BODY_B64="${4:-}"
if [[ -z "$AREA" || -z "$NAME" || -z "$BODY_B64" ]]; then
  echo "Usage: ./vm/custom_action_create.sh <area> <name> <desc> <body_base64>" >&2
  exit 1
fi

ACTIONS_BASE="${VM_ACTIONS_BASE:-/home/ubuntu/mcp-admin/actions}"
DESC_B64=$(printf '%s' "$DESC" | base64)

ssh -i "$VM_SSH_KEY" "$VM_USER@$VM_HOST" \
  "AREA='$AREA' NAME='$NAME' DESC_B64='$DESC_B64' BODY_B64='$BODY_B64' ACTIONS_BASE='$ACTIONS_BASE' bash -lc 'set -euo pipefail;\
    mkdir -p "$ACTIONS_BASE/$AREA";\
    path="$ACTIONS_BASE/$AREA/${NAME}.sh";\
    desc=$(echo "$DESC_B64" | base64 -d);\
    body=$(echo "$BODY_B64" | base64 -d);\
    cat > "$path" << EOF_CMD\
#!/usr/bin/env bash\
# ${desc}\
# Auto-generated by toolbox UI\
# Area: ${AREA}\
# Name: ${NAME}\
\
${body}\
EOF_CMD\
    chmod +x "$path";\
    echo "Created $path"'"
